#!/bin/bash
# retro-scan.sh — runtime-agnostic retro prep engine (Tier-1 substrate).
#
# Gathers the raw data for a weekly/monthly retro from the BRAIN (not the
# retired obsidian-vault) and from all three runtimes' memory layers, then
# emits a prep brief to the brain. The interactive interview stays a thin
# per-runtime layer (Claude skill / Codex prompt / Hermes cron) that reads
# this brief.
#
# TRI-RUNTIME CONTRACT — any runtime invokes the same way:
#   bash ~/site/skills/pandastack/plugins/pandastack/scripts/retro-scan.sh week   # 7-day
#   bash ~/site/skills/pandastack/plugins/pandastack/scripts/retro-scan.sh month  # 30-day
#   - Claude: retro-week / retro-month skills call this in Phase 1.
#   - Hermes: a cron job runs this to pre-generate the brief (deliver=local).
#   - Codex : a prompt/exec runs this, then conducts the interview.
# Pure bash + git + gbrain. No CLI-specific deps. Missing sources degrade to
# a noted skip, never an error.
set -uo pipefail
export PATH="/Users/panda/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"
export HOME="${HOME:-/Users/panda}"

MODE="${1:-week}"
case "$MODE" in
  week)  DAYS=7;  LABEL="WEEK";  TAG="$(date +%Y)-W$(date +%V)";;
  month) DAYS=30; LABEL="MONTH"; TAG="$(date +%Y-%m)";;
  *) echo "usage: retro-scan.sh week|month" >&2; exit 2;;
esac
SINCE="${DAYS} days ago"
SINCE_DATE=$(date -v-"${DAYS}"d +%Y-%m-%d 2>/dev/null || date -d "-${DAYS} days" +%Y-%m-%d)

BRAIN="$HOME/site/knowledge/brain"
OUT_DIR="$BRAIN/inbox/retros"
OUT="$OUT_DIR/${SINCE_DATE}-retro-${MODE}-prep.md"
mkdir -p "$OUT_DIR"

{
  echo "---"
  echo "name: ${SINCE_DATE}-retro-${MODE}-prep"
  echo "description: Auto-generated ${MODE} retro prep brief (brain-sourced, tri-runtime engine)."
  echo "metadata:"
  echo "  type: report"
  echo "---"
  echo
  echo "# ${LABEL} RETRO PREP — ${TAG}  (${SINCE_DATE} → today)"
  echo
  echo "> Generated by retro-scan.sh. Raw data only — no interpretation. The interview layer validates."
  echo

  # ---- 1. Git activity (brain + ~/site repos) ----
  echo "## Git activity (past ${DAYS}d)"
  if [ -d "$BRAIN/.git" ]; then
    n=$(git -C "$BRAIN" log --since="$SINCE" --oneline --no-merges 2>/dev/null | wc -l | tr -d ' ')
    echo "- [brain] ${n} commits"
  fi
  for d in "$HOME/site/skills/"* "$HOME/site/apps/"* "$HOME/site/cli/"* "$HOME/site/trading/"*; do
    [ -d "$d/.git" ] || continue
    n=$(git -C "$d" log --since="$SINCE" --oneline --no-merges 2>/dev/null | wc -l | tr -d ' ')
    [ "${n:-0}" -gt 0 ] && echo "- [$(basename "$d")] ${n} commits"
  done
  echo

  # ---- 2. Learnings health (brain/learnings) ----
  echo "## Learnings health"
  LDIR="$BRAIN/learnings"
  if [ -d "$LDIR" ]; then
    total=$(find "$LDIR" -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
    fresh=$(find "$LDIR" -name '*.md' -mtime -"${DAYS}" 2>/dev/null | wc -l | tr -d ' ')
    stale=$(find "$LDIR" -name '*.md' -mtime +90 2>/dev/null | wc -l | tr -d ' ')
    echo "- Total: ${total} | New this ${MODE}: ${fresh} | Stale (90d+): ${stale}"
  else
    echo "- learnings/ not found — skip"
  fi
  echo

  # ---- 3. Recent brain activity (sessions / decisions / reflections) ----
  echo "## Recent brain pages (past ${DAYS}d, by dir)"
  for sub in sessions decisions reflections/daily plans projects; do
    [ -d "$BRAIN/$sub" ] || continue
    files=$(find "$BRAIN/$sub" -name '*.md' -mtime -"${DAYS}" 2>/dev/null | sort)
    cnt=$(echo "$files" | grep -c . )
    [ "${cnt:-0}" -eq 0 ] && continue
    echo "### $sub (${cnt})"
    echo "$files" | head -12 | while read -r f; do [ -n "$f" ] && echo "- $(basename "$f" .md)"; done
    echo
  done

  # ---- 4. gbrain synthesis (if available) ----
  echo "## Brain synthesis (gbrain)"
  if command -v gbrain >/dev/null 2>&1; then
    echo "_Salient pages updated since ${SINCE_DATE}:_"
    gbrain query "salient pages updated since ${SINCE_DATE}" 2>/dev/null | head -12 | sed 's/^/- /'
  else
    echo "- gbrain not on PATH — synthesis skipped"
  fi
  echo

  # ---- 5. GC sweep: recent feedback across ALL THREE runtimes ----
  echo "## GC sweep — recent memory feedback (past ${DAYS}d, all runtimes)"
  echo "_Each feedback file = a forcing function that did not fire. Interview decides which become mechanism._"
  # Claude Code: per-project memory
  cc=$(find "$HOME/.claude/projects" -mindepth 3 -maxdepth 3 -path '*/memory/feedback_*.md' -mtime -"${DAYS}" 2>/dev/null)
  # Substrate (shared, read by Codex + all CLIs)
  sub=$(find "$HOME/.agents/memory" -name 'feedback_*.md' -mtime -"${DAYS}" 2>/dev/null)
  # Hermes
  her=$(find "$HOME/.hermes/memories" -name '*.md' -mtime -"${DAYS}" 2>/dev/null)
  for src in "claude:$cc" "substrate:$sub" "hermes:$her"; do
    rt="${src%%:*}"; list="${src#*:}"
    [ -z "$list" ] && continue
    echo "### [$rt]"
    echo "$list" | while read -r f; do
      [ -z "$f" ] && continue
      name=$(grep -m1 '^name:' "$f" 2>/dev/null | sed 's/name:[[:space:]]*//')
      echo "- ${name:-$(basename "$f")}"
    done
  done
  # Codex uses a sqlite memory store (~/.codex/memories_1.sqlite) — not markdown.
  echo "- [codex] memory is sqlite (~/.codex/memories_*.sqlite) — inspect separately if needed"
  echo

  # ---- 6. Inbox drain: unfiled transcript-ingest distills (counts only) ----
  # --count, NOT the full report: this brief auto-commits to public GitHub, and
  # the per-file list contains work-domain slugs that would reveal private topics.
  # Run the full per-domain report locally during the interview.
  echo "## INBOX DRAIN — unfiled transcript-ingest distills"
  TRIAGE="$HOME/gbrain/skills/transcript-ingest/lib/triage_inbox.sh"
  if [ -x "$TRIAGE" ]; then
    "$TRIAGE" --count | sed 's/^/- /'
    echo "_Full per-domain list (per-domain destinations): run \`$TRIAGE\` locally — not committed._"
  else
    echo "- triage_inbox.sh not found — skip"
  fi
  echo

  echo "---"
  echo "_End prep. Interview layer: validate, don't auto-write recommendations._"
} > "$OUT"

echo "$OUT"
